import type { Phoneme } from './types'

const DUMMY_DESCRIPTION = 'この音の発音方法の説明がここに入ります。'

const phonemes: Phoneme[] = [
  // === Consonants (24) ===
  // Plosives (6)
  {
    symbol: 'p',
    displaySymbol: '/p/',
    category: 'consonant',
    subcategory: 'plosive',
    voicing: '無声',
    articulationPoint: '両唇',
    exampleWord: 'pat',
    elsaNotation: '/pæt/',
    japaneseApprox: 'パ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'b',
    displaySymbol: '/b/',
    category: 'consonant',
    subcategory: 'plosive',
    voicing: '有声',
    articulationPoint: '両唇',
    exampleWord: 'bat',
    elsaNotation: '/bæt/',
    japaneseApprox: 'バ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 't',
    displaySymbol: '/t/',
    category: 'consonant',
    subcategory: 'plosive',
    voicing: '無声',
    articulationPoint: '歯茎',
    exampleWord: 'top',
    elsaNotation: '/tɑp/',
    japaneseApprox: 'タ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'd',
    displaySymbol: '/d/',
    category: 'consonant',
    subcategory: 'plosive',
    voicing: '有声',
    articulationPoint: '歯茎',
    exampleWord: 'dog',
    elsaNotation: '/dɑg/',
    japaneseApprox: 'ダ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'k',
    displaySymbol: '/k/',
    category: 'consonant',
    subcategory: 'plosive',
    voicing: '無声',
    articulationPoint: '軟口蓋',
    exampleWord: 'cat',
    elsaNotation: '/kæt/',
    japaneseApprox: 'カ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'g',
    displaySymbol: '/g/',
    category: 'consonant',
    subcategory: 'plosive',
    voicing: '有声',
    articulationPoint: '軟口蓋',
    exampleWord: 'go',
    elsaNotation: '/goʊ/',
    japaneseApprox: 'ガ行',
    description: DUMMY_DESCRIPTION,
  },

  // Fricatives (9)
  {
    symbol: 'f',
    displaySymbol: '/f/',
    category: 'consonant',
    subcategory: 'fricative',
    voicing: '無声',
    articulationPoint: '唇歯',
    exampleWord: 'fan',
    elsaNotation: '/fæn/',
    japaneseApprox: 'ファ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'v',
    displaySymbol: '/v/',
    category: 'consonant',
    subcategory: 'fricative',
    voicing: '有声',
    articulationPoint: '唇歯',
    exampleWord: 'van',
    elsaNotation: '/væn/',
    japaneseApprox: 'ヴァ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'θ',
    displaySymbol: '/θ/',
    category: 'consonant',
    subcategory: 'fricative',
    voicing: '無声',
    articulationPoint: '歯',
    exampleWord: 'think',
    elsaNotation: '/θɪŋk/',
    japaneseApprox: 'サ行に近い（舌先を歯に）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ð',
    displaySymbol: '/ð/',
    category: 'consonant',
    subcategory: 'fricative',
    voicing: '有声',
    articulationPoint: '歯',
    exampleWord: 'this',
    elsaNotation: '/ðɪs/',
    japaneseApprox: 'ザ行に近い（舌先を歯に）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 's',
    displaySymbol: '/s/',
    category: 'consonant',
    subcategory: 'fricative',
    voicing: '無声',
    articulationPoint: '歯茎',
    exampleWord: 'sun',
    elsaNotation: '/sʌn/',
    japaneseApprox: 'サ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'z',
    displaySymbol: '/z/',
    category: 'consonant',
    subcategory: 'fricative',
    voicing: '有声',
    articulationPoint: '歯茎',
    exampleWord: 'zoo',
    elsaNotation: '/zu/',
    japaneseApprox: 'ザ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ʃ',
    displaySymbol: '/ʃ/',
    category: 'consonant',
    subcategory: 'fricative',
    voicing: '無声',
    articulationPoint: '後部歯茎',
    exampleWord: 'she',
    elsaNotation: '/ʃi/',
    japaneseApprox: 'シャ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ʒ',
    displaySymbol: '/ʒ/',
    category: 'consonant',
    subcategory: 'fricative',
    voicing: '有声',
    articulationPoint: '後部歯茎',
    exampleWord: 'measure',
    elsaNotation: '/mɛʒər/',
    japaneseApprox: 'ジャ行に近い',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'h',
    displaySymbol: '/h/',
    category: 'consonant',
    subcategory: 'fricative',
    voicing: '無声',
    articulationPoint: '声門',
    exampleWord: 'hat',
    elsaNotation: '/hæt/',
    japaneseApprox: 'ハ行',
    description: DUMMY_DESCRIPTION,
  },

  // Affricates (2)
  {
    symbol: 'tʃ',
    displaySymbol: '/tʃ/',
    category: 'consonant',
    subcategory: 'affricate',
    voicing: '無声',
    articulationPoint: '後部歯茎',
    exampleWord: 'church',
    elsaNotation: '/tʃɝtʃ/',
    japaneseApprox: 'チャ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'dʒ',
    displaySymbol: '/dʒ/',
    category: 'consonant',
    subcategory: 'affricate',
    voicing: '有声',
    articulationPoint: '後部歯茎',
    exampleWord: 'judge',
    elsaNotation: '/dʒʌdʒ/',
    japaneseApprox: 'ジャ行',
    description: DUMMY_DESCRIPTION,
  },

  // Nasals (3)
  {
    symbol: 'm',
    displaySymbol: '/m/',
    category: 'consonant',
    subcategory: 'nasal',
    voicing: '有声',
    articulationPoint: '両唇',
    exampleWord: 'man',
    elsaNotation: '/mæn/',
    japaneseApprox: 'マ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'n',
    displaySymbol: '/n/',
    category: 'consonant',
    subcategory: 'nasal',
    voicing: '有声',
    articulationPoint: '歯茎',
    exampleWord: 'no',
    elsaNotation: '/noʊ/',
    japaneseApprox: 'ナ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ŋ',
    displaySymbol: '/ŋ/',
    category: 'consonant',
    subcategory: 'nasal',
    voicing: '有声',
    articulationPoint: '軟口蓋',
    exampleWord: 'sing',
    elsaNotation: '/sɪŋ/',
    japaneseApprox: '「ン」（カ行の前）',
    description: DUMMY_DESCRIPTION,
  },

  // Liquids (2)
  {
    symbol: 'l',
    displaySymbol: '/l/',
    category: 'consonant',
    subcategory: 'liquid',
    exampleWord: 'let',
    elsaNotation: '/lɛt/',
    japaneseApprox: 'ラ行に近い（舌先を歯茎に）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'r',
    displaySymbol: '/r/',
    category: 'consonant',
    subcategory: 'liquid',
    exampleWord: 'red',
    elsaNotation: '/rɛd/',
    japaneseApprox: 'ラ行に近い（舌を巻く）',
    description: DUMMY_DESCRIPTION,
  },

  // Glides (2)
  {
    symbol: 'w',
    displaySymbol: '/w/',
    category: 'consonant',
    subcategory: 'glide',
    articulationPoint: '両唇軟口蓋',
    exampleWord: 'we',
    elsaNotation: '/wi/',
    japaneseApprox: 'ワ行',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'j',
    displaySymbol: '/j/',
    category: 'consonant',
    subcategory: 'glide',
    articulationPoint: '硬口蓋',
    exampleWord: 'yes',
    elsaNotation: '/jɛs/',
    japaneseApprox: 'ヤ行',
    description: DUMMY_DESCRIPTION,
  },

  // === Monophthongs (11) ===
  // Front Vowels (4)
  {
    symbol: 'i',
    displaySymbol: '/i/',
    category: 'monophthong',
    subcategory: 'front-vowel',
    openness: '狭（閉）',
    exampleWord: 'feet',
    elsaNotation: '/fit/',
    japaneseApprox: '「イー」（長め）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɪ',
    displaySymbol: '/ɪ/',
    category: 'monophthong',
    subcategory: 'front-vowel',
    openness: '半狭',
    exampleWord: 'sit',
    elsaNotation: '/sɪt/',
    japaneseApprox: '「イ」（短く弛緩）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɛ',
    displaySymbol: '/ɛ/',
    category: 'monophthong',
    subcategory: 'front-vowel',
    openness: '半広',
    exampleWord: 'bed',
    elsaNotation: '/bɛd/',
    japaneseApprox: '「エ」',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'æ',
    displaySymbol: '/æ/',
    category: 'monophthong',
    subcategory: 'front-vowel',
    openness: '広',
    exampleWord: 'cat',
    elsaNotation: '/kæt/',
    japaneseApprox: '「ア」と「エ」の間',
    description: DUMMY_DESCRIPTION,
  },

  // Central Vowels (3)
  {
    symbol: 'ə',
    displaySymbol: '/ə/',
    category: 'monophthong',
    subcategory: 'central-vowel',
    openness: '中央（弱）',
    exampleWord: 'about',
    elsaNotation: '/əbaʊt/',
    japaneseApprox: '曖昧な「ア」（弱く短い）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ʌ',
    displaySymbol: '/ʌ/',
    category: 'monophthong',
    subcategory: 'central-vowel',
    openness: '半広',
    exampleWord: 'cup',
    elsaNotation: '/kʌp/',
    japaneseApprox: '「ア」（短く強め）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɝ',
    displaySymbol: '/ɝ/',
    category: 'monophthong',
    subcategory: 'central-vowel',
    openness: '中央（R音化・強勢）',
    exampleWord: 'bird',
    elsaNotation: '/bɝd/',
    japaneseApprox: '「アー」＋舌巻き',
    description: DUMMY_DESCRIPTION,
  },

  // Back Vowels (4)
  {
    symbol: 'u',
    displaySymbol: '/u/',
    category: 'monophthong',
    subcategory: 'back-vowel',
    openness: '狭（閉）',
    exampleWord: 'boot',
    elsaNotation: '/but/',
    japaneseApprox: '「ウー」（唇丸め）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ʊ',
    displaySymbol: '/ʊ/',
    category: 'monophthong',
    subcategory: 'back-vowel',
    openness: '半狭',
    exampleWord: 'foot',
    elsaNotation: '/fʊt/',
    japaneseApprox: '「ウ」（短く弛緩）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɔ',
    displaySymbol: '/ɔ/',
    category: 'monophthong',
    subcategory: 'back-vowel',
    openness: '半広',
    exampleWord: 'thought',
    elsaNotation: '/θɔt/',
    japaneseApprox: '「オー」（唇丸め）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɑ',
    displaySymbol: '/ɑ/',
    category: 'monophthong',
    subcategory: 'back-vowel',
    openness: '広',
    exampleWord: 'father',
    elsaNotation: '/fɑðər/',
    japaneseApprox: '「ア」（口を大きく）',
    description: DUMMY_DESCRIPTION,
  },

  // === Diphthongs (5) ===
  {
    symbol: 'eɪ',
    displaySymbol: '/eɪ/',
    category: 'diphthong',
    subcategory: 'diphthong',
    movement: '前舌→狭',
    exampleWord: 'say',
    elsaNotation: '/seɪ/',
    japaneseApprox: '「エイ」',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'aɪ',
    displaySymbol: '/aɪ/',
    category: 'diphthong',
    subcategory: 'diphthong',
    movement: '広→狭',
    exampleWord: 'time',
    elsaNotation: '/taɪm/',
    japaneseApprox: '「アイ」',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɔɪ',
    displaySymbol: '/ɔɪ/',
    category: 'diphthong',
    subcategory: 'diphthong',
    movement: '後舌→狭',
    exampleWord: 'boy',
    elsaNotation: '/bɔɪ/',
    japaneseApprox: '「オイ」',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'oʊ',
    displaySymbol: '/oʊ/',
    category: 'diphthong',
    subcategory: 'diphthong',
    movement: '後舌→狭',
    exampleWord: 'go',
    elsaNotation: '/goʊ/',
    japaneseApprox: '「オウ」',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'aʊ',
    displaySymbol: '/aʊ/',
    category: 'diphthong',
    subcategory: 'diphthong',
    movement: '広→後舌狭',
    exampleWord: 'now',
    elsaNotation: '/naʊ/',
    japaneseApprox: '「アウ」',
    description: DUMMY_DESCRIPTION,
  },

  // === R-colored Vowels (7) ===
  {
    symbol: 'ɝ',
    displaySymbol: '/ɝ/',
    category: 'r-colored',
    subcategory: 'r-colored-vowel',
    exampleWord: 'bird',
    elsaNotation: '/bɝd/',
    japaneseApprox: '「アー」＋舌巻き（強勢）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ər',
    displaySymbol: '/ər/',
    category: 'r-colored',
    subcategory: 'r-colored-vowel',
    exampleWord: 'butter',
    elsaNotation: '/bʌtər/',
    japaneseApprox: '「ア」＋舌巻き（弱勢）',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɑr',
    displaySymbol: '/ɑr/',
    category: 'r-colored',
    subcategory: 'r-colored-vowel',
    exampleWord: 'car',
    elsaNotation: '/kɑr/',
    japaneseApprox: '「アー」＋舌巻き',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɔr',
    displaySymbol: '/ɔr/',
    category: 'r-colored',
    subcategory: 'r-colored-vowel',
    exampleWord: 'door',
    elsaNotation: '/dɔr/',
    japaneseApprox: '「オー」＋舌巻き',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɪr',
    displaySymbol: '/ɪr/',
    category: 'r-colored',
    subcategory: 'r-colored-vowel',
    exampleWord: 'here',
    elsaNotation: '/hɪr/',
    japaneseApprox: '「イア」＋舌巻き',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ɛr',
    displaySymbol: '/ɛr/',
    category: 'r-colored',
    subcategory: 'r-colored-vowel',
    exampleWord: 'there',
    elsaNotation: '/ðɛr/',
    japaneseApprox: '「エア」＋舌巻き',
    description: DUMMY_DESCRIPTION,
  },
  {
    symbol: 'ʊr',
    displaySymbol: '/ʊr/',
    category: 'r-colored',
    subcategory: 'r-colored-vowel',
    exampleWord: 'sure',
    elsaNotation: '/ʃʊr/',
    japaneseApprox: '「ウア」＋舌巻き',
    description: DUMMY_DESCRIPTION,
  },
]

export const ALL_PHONEMES: readonly Phoneme[] = Object.freeze(phonemes.map((p) => Object.freeze(p)))
